CREATE DATABASE viongJewellery; -- DB 생성

CREATE USER 'viongJewellery'@'%' IDENTIFIED BY 'viongJewellery';  -- 계정 생성

GRANT ALL PRIVILEGES ON viongJewellery.* TO 'viongJewellery'@'%'; -- 권한부여

FLUSH PRIVILEGES; -- 권한 즉시 적용


CREATE TABLE CODE (
    CODE VARCHAR(15) PRIMARY KEY COMMENT '코드',
    CODE_NAME VARCHAR(100) NOT NULL COMMENT '코드명',
    UP_CODE VARCHAR(15) COMMENT '상위코드',
    SORT NUMERIC(3) COMMENT '정렬',
    ETC01 VARCHAR(100) COMMENT '기타1',
    ETC02 VARCHAR(100) COMMENT '기타2',
    USE_YN CHAR(1) COMMENT '사용여부'
)COMMENT='공통코드 테이블';



CREATE TABLE PRODUCT (
   SEQ INT AUTO_INCREMENT PRIMARY KEY COMMENT '번호',
  NAME varchar(30) NOT NULL COMMENT '제품이름',
  HAND_EXPENSES int NOT NULL COMMENT '수공비',
  WEIGHT int NOT NULL COMMENT '중량',
  SIZE int NOT NULL COMMENT '사이즈',
  STOCK int NOT NULL COMMENT '재고',
  CONTENT varchar(100) NOT NULL COMMENT '제품설명',
  IMAGE varchar(100) NOT NULL COMMENT '제품이미지',
  STATUS_CODE varchar(10) NOT NULL COMMENT '제품상태',
  CATEGORY_CODE varchar(10) NOT NULL COMMENT '제품분류'
  );
